# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46e4fba3eef7a7974f85eb0c6ae78e36e58d7beec70a119a41f4a8fb9c9d993e6f3485dc9f3ba95fecca9b2e7602876c09c393d49551bbae1cfbaef28c1e201c

test:
  secret_key_base: 31d8682d3379230f3d8331e2ec0b65522fce2c85b67eb0b780f6cd84f01e5530d0d49693d2b531fc6e6f81af2f84b662aafda0c8b49f95698d4750d1e0e1b2ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
